from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio

@register(outgoing=True, pattern="^.amb$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("**AMBULANCE**")
        sleep(1)
        await e.edit("**HARAP**")        
        await e.edit("**MINGGIR**")
        sleep(1)        
        await e.edit("**WIYUU WIYUU**\n🔵🔵⬜⬜🔴🔴\n🔵🔵⬜⬜🔴🔴")        
        await e.edit("**WIYUU WIYUU**\n🔴🔴⬜⬜🔵🔵\n🔴🔴⬜⬜🔵🔵")        
        await e.edit("**WIYUU WIYUU**\n🔵🔵⬜⬜🔴🔴\n🔵🔵⬜⬜🔴🔴")        
        await e.edit("**WIYUU WIYUU**\n🔴🔴⬜⬜🔵🔵\n🔴🔴⬜⬜🔵🔵")
        await e.edit("**WIYUU WIYUU**\n🔵🔵⬜⬜🔴🔴\n🔵🔵⬜⬜🔴🔴")        
        await e.edit("**WIYUU WIYUU**\n🔴🔴⬜⬜🔵🔵\n🔴🔴⬜⬜🔵🔵")        
        await e.edit("**WIYUU WIYUU**\n🔵🔵⬜⬜🔴🔴\n🔵🔵⬜⬜🔴🔴")        
        await e.edit("**WIYUU WIYUU**\n🔴🔴⬜⬜🔵🔵\n🔴🔴⬜⬜🔵🔵")
        await e.edit("**WIYUU WIYUU**\n🔵🔵⬜⬜🔴🔴\n🔵🔵⬜⬜🔴🔴")        
        await e.edit("**WIYUU WIYUU**\n🔴🔴⬜⬜🔵🔵\n🔴🔴⬜⬜🔵🔵")        
        sleep(1)
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏡🏠🏬\n                               🚑\n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏡🏠🏬\n                             🚑  \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏡🏠🏬\n                          🚑     \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n                       🚑        \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n                    🚑           \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n                 🚑              \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n              🚑                 \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n                  🚑             \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n               🚑                \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n             🚑                  \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n           🚑                    \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n         🚑                      \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n       🚑                        \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n      🚑                         \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n    🚑                           \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n  🚑                             \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🌲🌲🏢🏦🏢🌲🌲🏠🏠🏬\n🚑                               \n═════════════════\n🚗 🚙 🚌 🚕 🚕 🚗 🚚 🚛")
        await e.edit("🏥🌳🌳🌳🌳\n              🚑\n════════")
        await e.edit("🏥🌳🌳🌳🌳\n          🚑    \n════════")
        await e.edit("🏥🌳🌳🌳🌳\n      🚑        \n════════")
        await e.edit("🏥🌳🌳🌳🌳\n  🚑            \n════════")
        await e.edit("🏥🌳🌳🌳🌳\n🚑              \n════════")
        sleep(2)
        await e.edit("**ALHAMDULILLAH**")
        sleep(1)
        await e.edit("**UDAH SAMPAI**")
        sleep(1)
        await e.edit("**DENGAN SELAMAT**")
        sleep(1)
        await e.edit("🏥")
